server:
  port: 8003

spring:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL5Dialect
    datasource:
      url: jdbc:mysql://localhost:3306/smart_school
      username: root
      password: welcome
