server:
  port: 8003

spring:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    datasource:
      url: jdbc:mysql://localhost:3306/smart_school
      username: root
      password:
